[build]
command = "bun install && bunx prisma generate && bun run build"

[deploy]
startCommand = "bunx prisma migrate deploy && bun run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
